### ISSUE TITLE
Musl Support

### ISSUE THREAD

**Issue by skyne98** [NVIDIA/nvidia-installer#10]
Hey, there, is there any way to install Nvidia driver on a Musl platform such as Alpine?

**Comment by HarpyX** [comment]
i guess the title should be, please provide driver for muslc, so we can install it on musl linux distros and probably would also work on openbsd.
you guys really should do this. as far as i know you just need to compile it with musl, so it should not take much work. there is people trying to use your graphic cards with openbsd and void linux possible other os with musl, not having drivers for musl forces people to buy amd cards.

**Comment by HarpyEagleMan** [comment]
Same problem here

**Comment by aaronp24** [comment]
Thanks for filing this. While we have no plans to support Musl at this time, it is helpful to know where customer interest lies.

**Comment by bogheanul** [comment]
NVIDIA should really work around musl(&FullPOSIX, in general) the smaller complexities, smarter optimizations, the best for everyone. I would really try to deal with Alpine if I could have access to my GTX1660 ... Even closed-source drivers are far from their best and I will only mention 'nvidia-persistence' user group (which for me it's a surplus of complexity): If they would have done a proper DRM kernel-build driver that akward strange thing shouldn't exist. So, for me, the smaller complexity, the better. Everything amplified by the highest standards/ best practices of computer sience(maybe Rust is the way) ... 

Even on Microsoft OS, if I debloat and let the pure driver, playing some games bring tremendous problems, which denote the fact that they are poor programmers, always basing on perpetuous cheap patches and silly tweaks. (And this is a story that has decades oldness) Remember the goold old days when we could enable pipelines for a better graphic card ? All those are gone. 

Firmwares should be entierly open-source. by the way, I would like to use a SLI between AMD and NVIDIA but the driver to use the entire juice for that is light-years away. (As example, I can't even turn of my GPU cooler down, as my old same MSI manufacturer card could do, under 47% :| And I will not risk the warranty and even 'destroying'  my graphic card ... 

FullOff-topic but still ...

**Comment by ra1nst0rm3d** [comment]
Due to the fact that NVIDIA does not support musl, my next purchase will be a video card from AMD...

**Comment by ilovecringe** [comment]
NVIDIA, it's time to open your drivers!

**Comment by nvidiaLinuxUser** [comment]
The problem is still relevant

**Comment by TheMBL09898** [comment]
Yes I'd like to see someone commenting about this as well.

**Comment by nvidiaLinuxUser** [comment]
@TheMBL09898, https://forums.developer.nvidia.com/t/provide-driver-for-muslc-to-install-it-in-musl-distros/219586

**Comment by xZero707** [comment]
As of 2023, still no support for muslc. I have an Alpine Linux-powered host that is optimized for containers. 
I have some Nvidia GPUs collecting dust, as I cannot use them in this machine. 
Shame. I have no plans to buy Nvidia ever again.

**Comment by oifj34f34f** [comment]
> I have no plans to buy Nvidia ever again - or at least until they show some more love to Linux community.

Same here

**Comment by Avsynthe** [comment]
The Docker world is absolutely begging for you to do this. There are so many great Alpine-based containers of applications that have GPU capabilities to greatly enhance their functionality. They're going to waste and are at a huge disadvantage. Don't you think it's time?

It may seem like there are not a lot of vocal users on this subject, that's because they're all in countless open-source project communities and discord chats that you'll never see out in the open. Make no mistake, this is a huge frustration across all communities.

**Comment by Saijin-Naib** [comment]
I sold all my NVIDIA hardware after using it exclusively since my MX420 PCI.

I need MUSL support because Alpine is my daily, and is far too good to go back from just because of a single GPU vendor.

**Comment by TheMBL09898** [comment]
NVIDIA continously shows disrespect towards its own customers in every area. Even though I understand that every company's focus is to increase profit I do not understand how such a simple feautre to implement can somehow interfere with that goal. Not just that, but forcing people to use propietary software to unlock the GPU's potential that we've paid for is inherently immoral, although we are not entitled to you providing true open source drivers: I must admit, I made a mistake buying from NVIDIA. When NVIDIA released their so-called "open source drivers" it became even clearer that they only care about their appearance: not us, free software enthusiasts. I am well aware that other companies do the same thing, but when both AMD and Intel have free drivers it becomes clear who cares more about the free software community. NVIDIA has drivers for FreeBSD, why the hell is it a problem to make the more used Linux driver compatible with another libc??? I'm selling my NVIDIA laptop and my next PC is not going to have a single NVIDIA chip in it.

**Comment by xZero707** [comment]
NVIDIA doesn't care because they can afford it; Unfortunately, whatever AI/ML project you decide to run, almost all paths eventually lead to CUDA, and therefore NVIDIA.

**Comment by Avsynthe** [comment]
It's 2024 now and still nothing :(. Great Alpine based containers with AI functionality wasting away. And all forms of Linux are seeing a huge push these days. Crazy Nvidia isn't trying to dominate every one of them

**Comment by szmarczak** [comment]
I have successfully installed NVIDIA drivers like [this](https://gist.github.com/szmarczak/146caaa8e9245532f076078c3d9e9146). 
However, running actual apps fails because of missing glibc-only symbols in `musl`. The following symbols are missing:

```
gnu_get_libc_version
__isinf
__sched_cpufree
__sched_cpualloc
__strdup
__secure_getenv
__rawmemchr
__isnan
__strtok_r
__strftime_l
__cmsg_nxthdr
backtrace
dlmopen
dlvsym
dladdr1
mallinfo
__register_atfork

# Required only by nvidia-installer
fts_set
fts_close
fts_read
fts_open
```

I have implemented them and ran with (root) `LD_PRELOAD=/lib/nvgnucompat.so`, however `sway` fails with:

```
Cannot access GL to populate EGLConfig list
```

It could be because `musl` does <ins>**not**</ins> support [`dlopen`](https://git.musl-libc.org/cgit/musl/tree/src/ldso/dlopen.c), `dlmopen`, `mallinfo`, `backtrace` or some other differences like [this](https://wiki.musl-libc.org/functional-differences-from-glibc) and [this](https://wiki.musl-libc.org/faq).

However, it should be possible to chroot to a glibc distro and run sway from there. The drawback is that all GUI apps need to be glibc then.

**Comment by szmarczak** [comment]
I confirm that's because of missing `dlopen`.

After many times of `patchelf --add-needed <library> /usr/bin/sway` it went through the EGL stuff but failed with
`Failed to get GL_EXTENSIONS`

I don't have more time for this, so if anybody wants to *somehow* create a huge `.so` file containing all nvidia libraries and symlink all the small parts to the huge one, feel free! Although it would be much easier to just `chroot` anyway.

[sway.alpine.log](https://github.com/user-attachments/files/15686266/sway.alpine.log)

sway dependency graph: [sway.json](https://github.com/user-attachments/files/15686291/sway.json)

**Comment by szmarczak** [comment]
Guys I fuckin' did it! It turns out I needed to symlink GLESv2 to the nvidia one!

In fact, I'm writing this on Chromium Alpine!

![image](https://github.com/NVIDIA/nvidia-installer/assets/36894700/440f5323-9a62-4b9b-994f-a272623a4ffa)
![image](https://github.com/NVIDIA/nvidia-installer/assets/36894700/d0ee1a65-ca75-420a-8a07-f8719491709f)

**Comment by szmarczak** [comment]
While this works with Sway and Chromium, unfortunately this is not a proper fix. Ideally `dlopen`, `dlsym` and `dladdr` would be implemented. I knew what DLs to add because I ran Sway beforehand on glibc-based distro with `LD_DEBUG=all` to get the dependencies. This is just a proof of concept. Or, nvidia could implement their own DL handling. Or use syscalls instead of standard C (that's what golang does).

Or, if they don't do `dladdr` nor `dlsym` and `dlopen` can be statically analyzed, we can just extract those and mark them as needed. The only drawback is that they would be always loaded no matter what. And loading all nvidia DLs is at least 480MB.

**Comment by szmarczak** [comment]
<details>
<summary>calls used by DLs</summary>

```
CALL  USED_BY
dlsym libEGL.so.1.1.0
dlsym libEGL.so.555.42.02
dlsym libEGL_nvidia.so.555.42.02
dlsym libGLESv1_CM_nvidia.so.555.42.02
dlsym libGLESv2_nvidia.so.555.42.02
dlsym libGLX.so.0
dlsym libGLX_nvidia.so.555.42.02
dlsym libGLdispatch.so.0
dlsym libOpenCL.so.1.0.0
dlsym libcuda.so.555.42.02
dlsym libcudadebugger.so.555.42.02
dlsym libnvcuvid.so.555.42.02
dlsym libnvidia-allocator.so.555.42.02
dlsym libnvidia-cfg.so.555.42.02
dlsym libnvidia-egl-gbm.so.1.1.1
dlsym libnvidia-egl-wayland.so.1.1.13
dlsym libnvidia-eglcore.so.555.42.02
dlsym libnvidia-encode.so.555.42.02
dlsym libnvidia-fbc.so.555.42.02
dlsym libnvidia-glcore.so.555.42.02
dlsym libnvidia-glsi.so.555.42.02
dlsym libnvidia-gtk2.so.555.42.02
dlsym libnvidia-gtk3.so.555.42.02
dlsym libnvidia-ml.so.555.42.02
dlsym libnvidia-ngx.so.555.42.02
dlsym libnvidia-opencl.so.555.42.02
dlsym libnvidia-opticalflow.so.555.42.02
dlsym libnvidia-ptxjitcompiler.so.555.42.02
dlsym libnvidia-rtcore.so.555.42.02
dlsym libnvoptix.so.555.42.02
dlsym libvdpau_nvidia.so.555.42.02
dlsym nvidia_drv.so
dlsym nvidia-cuda-mps-server
dlsym nvidia-installer
dlsym nvidia-ngx-updater
dlsym nvidia-persistenced
dlsym nvidia-powerd
dlsym nvidia-settings
dlsym nvidia-smi
dlsym nvidia-xconfig

dladdr libEGL.so.1.1.0
dladdr libcudadebugger.so.555.42.02
dladdr libnvidia-ngx.so.555.42.02
dladdr libnvidia-rtcore.so.555.42.02
dladdr libnvoptix.so.555.42.02
dladdr libvdpau_nvidia.so.555.42.02

dlvsym libEGL_nvidia.so.555.42.02
dlvsym libGLESv1_CM_nvidia.so.555.42.02
dlvsym libGLESv2_nvidia.so.555.42.02
dlvsym libcuda.so.555.42.02
dlvsym libnvcuvid.so.555.42.02
dlvsym libnvidia-cfg.so.555.42.02
dlvsym libnvidia-eglcore.so.555.42.02
dlvsym libnvidia-encode.so.555.42.02
dlvsym libnvidia-glcore.so.555.42.02
dlvsym libnvidia-ml.so.555.42.02
dlvsym libnvidia-opencl.so.555.42.02
dlvsym libnvidia-opticalflow.so.555.42.02
dlvsym libnvidia-pkcs11-openssl3.so.555.42.02
dlvsym libnvidia-pkcs11.so.555.42.02
dlvsym libnvoptix.so.555.42.02
dlvsym libvdpau_nvidia.so.555.42.02
dlvsym nvidia_drv.so
dlvsym nvidia-cuda-mps-control
dlvsym nvidia-cuda-mps-server
dlvsym nvidia-smi

dlopen libEGL.so.1.1.0
dlopen libEGL.so.555.42.02
dlopen libEGL_nvidia.so.555.42.02
dlopen libGLESv1_CM_nvidia.so.555.42.02
dlopen libGLESv2_nvidia.so.555.42.02
dlopen libGLX.so.0
dlopen libGLX_nvidia.so.555.42.02
dlopen libOpenCL.so.1.0.0
dlopen libcuda.so.555.42.02
dlopen libcudadebugger.so.555.42.02
dlopen libnvcuvid.so.555.42.02
dlopen libnvidia-allocator.so.555.42.02
dlopen libnvidia-cfg.so.555.42.02
dlopen libnvidia-eglcore.so.555.42.02
dlopen libnvidia-encode.so.555.42.02
dlopen libnvidia-fbc.so.555.42.02
dlopen libnvidia-glcore.so.555.42.02
dlopen libnvidia-glsi.so.555.42.02
dlopen libnvidia-gtk2.so.555.42.02
dlopen libnvidia-gtk3.so.555.42.02
dlopen libnvidia-ml.so.555.42.02
dlopen libnvidia-ngx.so.555.42.02
dlopen libnvidia-opencl.so.555.42.02
dlopen libnvidia-opticalflow.so.555.42.02
dlopen libnvidia-pkcs11-openssl3.so.555.42.02
dlopen libnvidia-pkcs11.so.555.42.02
dlopen libnvidia-ptxjitcompiler.so.555.42.02
dlopen libnvidia-rtcore.so.555.42.02
dlopen libnvoptix.so.555.42.02
dlopen libvdpau_nvidia.so.555.42.02
dlopen nvidia_drv.so
dlopen nvidia-cuda-mps-control
dlopen nvidia-cuda-mps-server
dlopen nvidia-installer
dlopen nvidia-ngx-updater
dlopen nvidia-persistenced
dlopen nvidia-powerd
dlopen nvidia-settings
dlopen nvidia-smi
dlopen nvidia-xconfig
```
</details>

At this point I believe it would be easier to patch `musl` than nvidia DLs.

**Comment by szmarczak** [comment]
However, X11 fails with:

```
Error relocating /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so: _nv005tls: initial-exec TLS resolves to dynamic definition in /usr/lib/libnvidia-tls.so.555.42.02
Error relocating /usr/lib/libnvidia-glcore.so.555.42.02: unsupported relocation type 37
```

I believe `chroot`ing is the only viable option.

**Comment by joadr** [comment]
@szmarczak this is huge news! could you provide a guide we can follow to achieve this? Have you tried installing `nvidia-container-toolkit`?

**Comment by nanotouch** [comment]
I only want to use nvidia-smi command,how to install the nvidia driver,tanks

**Comment by Borderliner** [comment]
@Raven-Singularity I believe only the kernel modules are open source now, not the entire driver that was compiled against glibc.

**Comment by h8d13** [comment]
I just came here to say I agree. And wtf how @szmarczak

**Comment by Itxaka** [comment]
2026 and still nothing....

**Comment by h8d13** [comment]
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/release-notes.html

Actually: `Allow driver libraries to be properly located in musl-based containers.`
It's something :D Altho that implies a `glibc` host. Let's say we are 25% there

**Comment by Borderliner** [comment]
Are Alpine containers this insignificant to NVIDIA? Come on!

**Comment by h8d13** [comment]
On a slightly less hacky note than @szmarczak 

I get about 17k `glmark2-wayland` score on a 3080Ti (i5-14600KF) using `nouveau` (real open source way hehe 👍 )

This is actually not too far off the Arch proprietary comparison:

```

    OpenGL Information
    GL_VENDOR:      NVIDIA Corporation
    GL_RENDERER:    NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2
    GL_VERSION:     4.6.0 NVIDIA 590.48.01
    Surface Config: buf=32 r=8 g=8 b=8 a=8 depth=24 stencil=0 samples=0
    Surface Size:   800x600 windowed
=======================================================

=======================================================
                                  glmark2 Score: 30693
=======================================================
```

Means we are ~56% of the way there :D

---

This is most of what I had to do (mostly used the Alpine wiki)

(Base install steps, hostname, dns, etc)
Setup polkit/seatd sway/otherWM

Use: `$ doas apk add mesa-dri-gallium mesa-va-gallium mesa-vulkan-nouveau flatpak xdg-desktop-portal dbus dbus-x11 ca-certificates p11-kit-trust p11-kit-server nss-tools`

`$ doas update-ca-certificates` 

Set-up flathub repos (this will pull in their own runtimes but sandboxed, not polluting host with glibc symbols)

ENV vars to get VAAPI flatpak to work:

```
export LIBVA_DRIVER_NAME=nouveau
export MESA_LOADER_DRIVER_OVERRIDE=nouveau
``` 
After that the browser feels much smoother.

From Wikipedia:

In 2024, lead engineer Ben Skeggs is hired by Nvidia, to continue working on the open source driver.[[33]](https://en.wikipedia.org/wiki/Nouveau_(software)#cite_note-33)

Hopefully this keeps going in this direction where prop becomes obsolete :) You can help here to make this happen: https://docs.kernel.org/gpu/nouveau.html

Last week I also asked the sway devs to remove some of the nvidia `--unsupported-gpu` flags: https://github.com/swaywm/sway/commit/992d201512a26b49f070f22b32e988d2bd51105e (so we can do more reverse engineering like @szmarczak did !)

**Comment by szmarczak** [comment]
@h8d13 I don't think we'll see musl support anytime soon. Last time I checked, the driver heavily relied on relocations (relocations are required if you don't want to have duplicated code) and the driver libraries itself are too big to be merged into one file. musl should implement more relocation types, that would be the best solution.

**Comment by h8d13** [comment]
That's why I think we should help nouveau catch up instead :D Then no proprietary blobs at all. Its already pretty usable to be honest I thought it would be 40% ^^ 

Also did you manage to keep going up in versions with your method ? Because your mapping would just get bigger and bigger no ?

**Comment by polarathene** [comment]
> Then no proprietary blobs at all.

Pretty sure it's required if you want something like CUDA?

I've heard of ZLUDA but I'm not familiar enough with what's being done there, I think it was just driver API compatibility for non-nvidia drivers to use the CUDA libs, which lack any source to build (nvidia supplies `.so`/`.a` only).

---

> https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/release-notes.html
> 
> Actually: `Allow driver libraries to be properly located in musl-based containers.` It's something :D Altho that implies a `glibc` host. Let's say we are 25% there

That appears to be referring to [this Dec 2025 issue + fix](https://github.com/NVIDIA/nvidia-container-toolkit/issues/1526). That's about discovering the host driver libraries that are bind mounted into the container, so no real relevance there outside of containers AFAIK?

As that issue linked notes, they used `gcompat` package which kind of gets you glibc compatibility shim with musl, but not quite. Depending on the symbols linked some aren't implemented and you'll get a bunch of failures.
- So that approach should work for you without a container too AFAIK, but with container support it's generally focused on compute, the rest of your app if relying on glibc symbols may not work so well with `gcompat` 🤔 
- You can however absolutely build an app that links glibc and uses those CUDA libraries in a musl container and not using musl libc itself, just configuring the `DT_RUNPATH` / `DT_RPATH` for your binary and any bundled libs (_or using `LD_LIBRARY_PATH`, but don't set that as a global ENV otherwise it'll mess with anything else in the container linking to musl_).

Although at that point (for containers) I'd just be wondering why you're bothering with Alpine in the first place.
- You can get quite competitive sized glibc based images (with better performance), and that works with nvidia nicely already without various musl related quirks/drawbacks.
- If it were a CUDA based workload that needs the huge libraries bundled into the image, then I'd really not understand why you'd want to pursue an Alpine container at that point...

---

> Are Alpine containers this insignificant to NVIDIA? Come on!

What reason would you have for running Alpine containers with nvidia support in them? (_I'm genuinely curious_)

**Comment by Borderliner** [comment]
@polarathene None, I just wanna use Nvidia graphics fully on musl-based Linux distros like Chimera Linux.

**Comment by polarathene** [comment]
> Chimera Linux

I tried to have a quick glance over that (seems like an interesting distro), but I only saw it's build system for binary packages was using containers?

Would I be correct that you didn't have an issue with Alpine containers specifically in that case (on a glibc host with working nvidia drivers), but more of an issue with a musl host? Or were you trying to run Chimera via a container and somehow use nvidia there?

If the distro doesn't support nvidia when it's the host OS, then I'm not quite sure why you'd expect it to have special support within a container. You'd presumably be running some additional binary you added to the container yourself not officially supported by the distro, and that binary was dependent upon nvidia libraries/driver?

---

I'm definitely interested in hearing more use-cases for when someone would want to use nvidia within a container that uses musl instead of glibc. One of the perks of containers is that you can effectively run software that isn't easily available on your host OS, so reasons for preferring a musl distro in the container for something dependent upon nvidia is odd to say the least 😅 

The discussion around native musl support in general, for musl-based distros regardless of containers is a different topic, and I think more relevant for this issue.

**Comment by Borderliner** [comment]
@polarathene No containers, just as a musl-based host OS for regular use.
