### ISSUE TITLE
check for plymouth and nomodeset

### ISSUE THREAD

**Issue by leberknecht** [NVIDIA/nvidia-installer#7]
Ahoi!

I have a geforce 1080 and ubuntu 17.10, and for me, in order to make the driver work, i had to do some stuff that the installer didnt took care of:
* blacklist the nouveau drivers
* disable plymouth by removing "quiet splash" from grub config
* add "nomodeset" to grub config
* update-grub
* update-initramfs

Apparently this is a quite common problem, as there are a lot of articles and stackoverflow threads about this, so i'm wondering: couldnt the driver take care of this? Maybe the plymouth is just a problem if you have an encrypted hard drive (so the effect was: plymouth screen comes up, but i couldnt enter anything in the password input field, like the keyboard wasnt working, as described here https://bugs.launchpad.net/ubuntu/+source/plymouth/+bug/1386005 ) 

Driver version 390.48

**Comment by dadap** [comment]
Hi,

Thank you for the suggestion. nvidia-installer is intended to be a distro-agnostic way to install the driver, and as such, it does not include support for rebuilding the initrd, as different distros use different tools and processes for generating the initrd.

On distros that package the NVIDIA driver, using the distro-provided packages will generally provide a better and more tightly integrated experience than using nvidia-installer. Ubuntu has a good quality package in its “restricted” component, which takes care of all of the necessary configuration for you.

If you wish to install the driver using nvidia-installer rather than the Ubuntu package, I believe that it ought to be sufficient to write a modeprobe configuration file to blacklist Nouveau and also disable Nouveau KMS with the modeset=0 parameter, then rebuild the initrd. This way, even if Plymouth is left enabled and Nouveau KMS isn’t disabled in the bootloader configuration, it will still prevent Nouveau from creating a KMS framebuffer, which should prevent Plymouth from starting. nvidia-installer will offer to write a modprobe configuration file to blacklist Nouveau and disable Nouveau KMS if it detects that Nouveau is loaded when attempting installation, but it will not rebuild the initrd, and instead directs you to do so using whatever procedure is appropriate for your distro.

**Comment by leberknecht** [comment]
Thank you for the detailed answer :)
